# this is my travis file Hello
sudo: required
services:
        - docker

before_install:
        - docker build -t 572b4aa7a058/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true 572b4aa7a058/docker-react npm run test
deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-739451421510"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
                        
