sudo:required
services:
        -docker

before_install:
        -docker build -t 572b4aa7a058/docker-react -f Dockerfile.dev .

script:
        -docker run -e CI=true 572b4aa7a058/docker-react npm run test

